# Generated by Django 4.1.1 on 2022-10-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_det_is_user_user_det_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_det',
            old_name='address',
            new_name='user_address',
        ),
    ]
