# Generated by Django 4.1.1 on 2022-10-31 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_address_user_det_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_det',
            name='user_address',
        ),
        migrations.AddField(
            model_name='user_det',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.place'),
        ),
    ]
