# Generated by Django 4.1.1 on 2022-11-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_det_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_det',
            name='password',
        ),
    ]
