# Generated by Django 4.1.1 on 2022-10-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_address_user_det_user_address'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_address', models.TextField()),
                ('floor', models.CharField(max_length=100, null=True)),
                ('land_mark', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user_det')),
            ],
        ),
    ]
