# Generated by Django 4.1.1 on 2022-10-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_category',
        ),
    ]
