# Generated by Django 4.1.1 on 2022-10-31 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_place_remove_user_det_user_address_user_det_place'),
        ('restaurant', '0011_old_cart_order_old_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.place'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
