# Generated by Django 4.1.1 on 2022-10-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurants_place_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_prepared',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
