# Generated by Django 4.1.1 on 2022-11-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_stat',
            field=models.CharField(default='Confirmed', max_length=50, null=True),
        ),
    ]
