# Generated by Django 4.1.1 on 2022-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_category_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
