# Generated by Django 4.1.1 on 2022-11-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_coupon_category_offers_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.FloatField(default=0),
        ),
    ]
